# Generated by Django 3.1.7 on 2021-05-26 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=200)),
                ('project_desc', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Usecase',
            fields=[
                ('usecase_id', models.AutoField(primary_key=True, serialize=False)),
                ('usecase_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField()),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generation.project')),
            ],
        ),
        migrations.CreateModel(
            name='Usecasespec',
            fields=[
                ('spec_id', models.AutoField(primary_key=True, serialize=False)),
                ('spec_actor', models.CharField(max_length=200)),
                ('spec_desc', models.CharField(max_length=200)),
                ('spec_precon', models.CharField(max_length=200)),
                ('spec_precon_object', models.CharField(max_length=200)),
                ('spec_postcon', models.CharField(max_length=200)),
                ('spec_postcon_object', models.CharField(max_length=200)),
                ('usecase_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generation.usecase')),
            ],
        ),
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('step_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_alter', models.BooleanField()),
                ('subject', models.CharField(max_length=200)),
                ('activity', models.CharField(max_length=200)),
                ('object', models.CharField(max_length=200)),
                ('spec_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generation.usecasespec')),
            ],
        ),
    ]
