# Generated by Django 3.1.7 on 2021-05-26 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='steps',
            old_name='spec_id',
            new_name='spec',
        ),
        migrations.RenameField(
            model_name='usecase',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='usecasespec',
            old_name='usecase_id',
            new_name='usecase',
        ),
    ]
