# Generated by Django 3.1.7 on 2021-05-30 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0002_auto_20210526_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='created_at',
        ),
    ]
