# Generated by Django 3.1.7 on 2021-06-11 14:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0003_remove_project_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usecase',
            name='actor',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='usecase',
            name='desc',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='usecase',
            name='postcon',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='usecase',
            name='postcon_object',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='usecase',
            name='precon',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='usecase',
            name='precon_object',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='usecase',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='steps',
            name='spec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generation.usecase'),
        ),
        migrations.AlterField(
            model_name='usecase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Usecasespec',
        ),
    ]
